# Generated by Django 5.0.3 on 2024-03-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_alter_menulink_new_tab_alter_menulink_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='new_tab',
            field=models.BooleanField(default=False, verbose_name='Abrir em nova aba'),
        ),
    ]
