# Generated by Django 5.0.3 on 2024-03-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_menulink_new_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Testo do link'),
        ),
    ]
