# Generated by Django 5.0.3 on 2024-03-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_sitesetup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Site'},
        ),
        migrations.AddField(
            model_name='menulink',
            name='site_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.sitesetup'),
        ),
    ]
